no_env: "Const with no env"

common: &common
  db_port: 3306
  nested:
    example:
      key: "value!"

test:
  <<: *common
  db_host: "test.example.com"

dev:
  <<: *common
  db_host: "dev.example.local"
